{% set name = "colcon-powershell" %}
{% set version = "0.3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/colcon/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 74ced69b0de09672de2aa2911c12bd7c64213fafb824570fda154e1e48ec3c9a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5
    - colcon-core >=0.3.18

test:
  imports:
    - {{ name.replace("-", "_") }}

about:
  home: https://github.com/colcon/{{ name }}
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    An extension for colcon-core to provide PowerShell scripts.

extra:
  recipe-maintainers:
    - seanyen
    - wolfv
