{% set name = "colcon-powershell" %}
{% set version = "0.5.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/colcon/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 7ebae8c729d663df2139f80da860647c742db9a36775dac7cc7b55a990189f45

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - colcon-core >=0.3.18

test:
  requires:
    - python {{ python_min }}
  imports:
    - {{ name.replace("-", "_") }}

about:
  home: https://github.com/colcon/{{ name }}
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    An extension for colcon-core to provide PowerShell scripts.

extra:
  recipe-maintainers:
    - j-rivero
    - seanyen
    - wolfv
